name: Release

on:
  push:
    tags: ["*"]
  workflow_dispatch:

permissions: {}

jobs:
  build-release:
    name: Build Release
    if: ${{ github.repository_owner == 'hugoschool' }}
    strategy:
      matrix:
        os: [ubuntu-26.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false

      - name: Build
        uses: ./.github/actions/build
        with:
          build-type: Release
          upload-artifact: true

  create-release:
    needs: [build-release]
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: r-type-*
          path: ./
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: ./r-type-*
          name: ${{ github.ref_name }}

